name: Compile LaTeX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: guide/00_instructivo.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: guide/00_instructivo.pdf
